package CareandCure;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class ShowInfo extends javax.swing.JFrame {

    /**
     * Creates new form ShowInfo
     */
        Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    public ShowInfo() {
        initComponents();
        show_user();
        con = Connect.ConnectDB();
        this.setLocationRelativeTo(null);
       
       
    }
    
     public ArrayList<User> userList(){
        
        ArrayList<User> userList = new ArrayList<>();
         
         try{
           
             con = Connect.ConnectDB();
            String query1 = "SELECT * FROM wardboy_nurse_tbl";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            User user;
            while(rs.next()){
                user=new User(rs.getInt("ID"),rs.getString("W_N_Name"),rs.getInt("Age"),rs.getString("Address"));
                userList.add(user);
            }
            
         }
            catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            }
         return userList;
        }
     public void show_user(){
          con = Connect.ConnectDB();
          ArrayList<User> list = userList();
          DefaultTableModel model = (DefaultTableModel)jTable_Display_User.getModel();
          Object[] row = new Object[4];
         for(int i=0;i<list.size();i++){
              row[0]=list.get(i).getID();
              row[1]=list.get(i).getW_N_Name();
              row[2]=list.get(i).getAge();
              row[3]=list.get(i).getAddress();
              model.addRow(row);
              
         }
     }
     public void clearTable()
{   
     con = Connect.ConnectDB();
    DefaultTableModel dm = (DefaultTableModel)jTable_Display_User.getModel();
    dm.getDataVector().removeAllElements();
    revalidate();
}
      
    
    
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Display_User = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        showall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Display_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Age", "Address"
            }
        ));
        jScrollPane1.setViewportView(jTable_Display_User);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Search:");

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        showall.setText("Show All");
        showall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showall, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(search))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(showall))
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Get_Data(){
    //String sql="SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl WHERE W_N_Name LIKE '%"+search.getText()+"%'";
      
    
    String sql="SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl WHERE ID LIKE '%"+search.getText()+"%'\n" +
"UNION  SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl WHERE  W_N_Name LIKE '%"+search.getText()+"%'\n" +
"UNION  SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl WHERE Age LIKE '%"+search.getText()+"%'\n" +
"UNION  SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl WHERE Address LIKE '%"+search.getText()+"%'";
    
    
    
    
//String sql= "SELECT * FROM wardboy_nurse_tbl name LIKE '%"+search.getText()+"%'";
         //sql+="UNION SELECT * FROM wardboy_nurse_tbl WHERE id LIKE '%"+search.getText()+"%'";
         //sql+="UNION SELECT * FROM wardboy_nurse_tbl WHERE age LIKE '%"+search.getText()+"%'";
  //       sql+="UNION SELECT * FROM wardboy_nurse_tbl WHERE patientsince LIKE '%"+search.getText()+"%'";    
//String sql="select NameOfUser as 'Name', UserName as 'User Name',Password,ContactNo as 'Contact No',Email as 'Email ID' from Registration";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         jTable_Display_User.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
private void Get_Data1(){
    String sql="SELECT ID,W_N_Name,Age,Address FROM wardboy_nurse_tbl";
        //String sql="select NameOfUser as 'Name', UserName as 'User Name',Password,ContactNo as 'Contact No',Email as 'Email ID' from Registration";
        try{
         pst=con.prepareStatement(sql);
          rs= pst.executeQuery();
         jTable_Display_User.setModel(DbUtils.resultSetToTableModel(rs));
         }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          
}
    }
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        Get_Data();
        
    }//GEN-LAST:event_okActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void showallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showallActionPerformed
        // TODO add your handling code here:
        
         Get_Data1();
        
    }//GEN-LAST:event_showallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Display_User;
    private javax.swing.JButton ok;
    private javax.swing.JTextField search;
    private javax.swing.JButton showall;
    // End of variables declaration//GEN-END:variables
}
